/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ApiTodoItemsRouteImport } from './routes/api/todo-items'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiBoardsRouteImport } from './routes/api/boards'
import { Route as ApiElectricTodoItemsRouteImport } from './routes/api/electric/todo-items'
import { Route as ApiElectricProjectsRouteImport } from './routes/api/electric/projects'
import { Route as ApiElectricBoardsRouteImport } from './routes/api/electric/boards'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiTodoItemsRoute = ApiTodoItemsRouteImport.update({
  id: '/api/todo-items',
  path: '/api/todo-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsRoute = ApiBoardsRouteImport.update({
  id: '/api/boards',
  path: '/api/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricTodoItemsRoute = ApiElectricTodoItemsRouteImport.update({
  id: '/api/electric/todo-items',
  path: '/api/electric/todo-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricProjectsRoute = ApiElectricProjectsRouteImport.update({
  id: '/api/electric/projects',
  path: '/api/electric/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricBoardsRoute = ApiElectricBoardsRouteImport.update({
  id: '/api/electric/boards',
  path: '/api/electric/boards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/api/boards': typeof ApiBoardsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todo-items': typeof ApiTodoItemsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/electric/boards': typeof ApiElectricBoardsRoute
  '/api/electric/projects': typeof ApiElectricProjectsRoute
  '/api/electric/todo-items': typeof ApiElectricTodoItemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/api/boards': typeof ApiBoardsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todo-items': typeof ApiTodoItemsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/electric/boards': typeof ApiElectricBoardsRoute
  '/api/electric/projects': typeof ApiElectricProjectsRoute
  '/api/electric/todo-items': typeof ApiElectricTodoItemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mobile': typeof MobileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/api/boards': typeof ApiBoardsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todo-items': typeof ApiTodoItemsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/electric/boards': typeof ApiElectricBoardsRoute
  '/api/electric/projects': typeof ApiElectricProjectsRoute
  '/api/electric/todo-items': typeof ApiElectricTodoItemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mobile'
    | '/projects'
    | '/api/boards'
    | '/api/projects'
    | '/api/todo-items'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/electric/boards'
    | '/api/electric/projects'
    | '/api/electric/todo-items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mobile'
    | '/api/boards'
    | '/api/projects'
    | '/api/todo-items'
    | '/projects/$projectId'
    | '/projects'
    | '/api/electric/boards'
    | '/api/electric/projects'
    | '/api/electric/todo-items'
  id:
    | '__root__'
    | '/'
    | '/mobile'
    | '/projects'
    | '/api/boards'
    | '/api/projects'
    | '/api/todo-items'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/electric/boards'
    | '/api/electric/projects'
    | '/api/electric/todo-items'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MobileRoute: typeof MobileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ApiBoardsRoute: typeof ApiBoardsRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiTodoItemsRoute: typeof ApiTodoItemsRoute
  ApiElectricBoardsRoute: typeof ApiElectricBoardsRoute
  ApiElectricProjectsRoute: typeof ApiElectricProjectsRoute
  ApiElectricTodoItemsRoute: typeof ApiElectricTodoItemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/todo-items': {
      id: '/api/todo-items'
      path: '/api/todo-items'
      fullPath: '/api/todo-items'
      preLoaderRoute: typeof ApiTodoItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards': {
      id: '/api/boards'
      path: '/api/boards'
      fullPath: '/api/boards'
      preLoaderRoute: typeof ApiBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/todo-items': {
      id: '/api/electric/todo-items'
      path: '/api/electric/todo-items'
      fullPath: '/api/electric/todo-items'
      preLoaderRoute: typeof ApiElectricTodoItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/projects': {
      id: '/api/electric/projects'
      path: '/api/electric/projects'
      fullPath: '/api/electric/projects'
      preLoaderRoute: typeof ApiElectricProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/boards': {
      id: '/api/electric/boards'
      path: '/api/electric/boards'
      fullPath: '/api/electric/boards'
      preLoaderRoute: typeof ApiElectricBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MobileRoute: MobileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ApiBoardsRoute: ApiBoardsRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiTodoItemsRoute: ApiTodoItemsRoute,
  ApiElectricBoardsRoute: ApiElectricBoardsRoute,
  ApiElectricProjectsRoute: ApiElectricProjectsRoute,
  ApiElectricTodoItemsRoute: ApiElectricTodoItemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
